/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VpseaRouteImport } from './routes/vpsea'
import { Route as UnifastRouteImport } from './routes/unifast'
import { Route as SuperRouteImport } from './routes/super'
import { Route as StudentRouteImport } from './routes/student'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VpseaIndexRouteImport } from './routes/vpsea.index'
import { Route as UnifastIndexRouteImport } from './routes/unifast.index'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as VpseaUploadsRouteImport } from './routes/vpsea.uploads'
import { Route as VpseaReportsRouteImport } from './routes/vpsea.reports'
import { Route as VpseaRenewalsRouteImport } from './routes/vpsea.renewals'
import { Route as VpseaArchivesRouteImport } from './routes/vpsea.archives'
import { Route as VpseaApplicationsRouteImport } from './routes/vpsea.applications'
import { Route as VpseaAnnouncementsRouteImport } from './routes/vpsea.announcements'
import { Route as VpseaAnalyticsRouteImport } from './routes/vpsea.analytics'
import { Route as UnifastTesRouteImport } from './routes/unifast.tes'
import { Route as UnifastTdpRouteImport } from './routes/unifast.tdp'
import { Route as UnifastReportsRouteImport } from './routes/unifast.reports'
import { Route as UnifastLiquidationRouteImport } from './routes/unifast.liquidation'
import { Route as UnifastFheRouteImport } from './routes/unifast.fhe'
import { Route as UnifastDistributionRouteImport } from './routes/unifast.distribution'
import { Route as UnifastContinuingRouteImport } from './routes/unifast.continuing'
import { Route as UnifastBillingRouteImport } from './routes/unifast.billing'
import { Route as UnifastAnalyticsRouteImport } from './routes/unifast.analytics'
import { Route as SuperUsersRouteImport } from './routes/super.users'
import { Route as SuperSettingsRouteImport } from './routes/super.settings'
import { Route as SuperOfficesRouteImport } from './routes/super.offices'
import { Route as SuperLogsRouteImport } from './routes/super.logs'
import { Route as SuperCategoriesRouteImport } from './routes/super.categories'
import { Route as SuperAnnouncementsRouteImport } from './routes/super.announcements'
import { Route as StudentRecommendationsRouteImport } from './routes/student.recommendations'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentApplicationsRouteImport } from './routes/student.applications'
import { Route as StudentApplyTdpRouteImport } from './routes/student.apply.tdp'
import { Route as StudentApplyAcademicRouteImport } from './routes/student.apply.academic'

const VpseaRoute = VpseaRouteImport.update({
  id: '/vpsea',
  path: '/vpsea',
  getParentRoute: () => rootRouteImport,
} as any)
const UnifastRoute = UnifastRouteImport.update({
  id: '/unifast',
  path: '/unifast',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VpseaIndexRoute = VpseaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VpseaRoute,
} as any)
const UnifastIndexRoute = UnifastIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnifastRoute,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const VpseaUploadsRoute = VpseaUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => VpseaRoute,
} as any)
const VpseaReportsRoute = VpseaReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => VpseaRoute,
} as any)
const VpseaRenewalsRoute = VpseaRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => VpseaRoute,
} as any)
const VpseaArchivesRoute = VpseaArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => VpseaRoute,
} as any)
const VpseaApplicationsRoute = VpseaApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => VpseaRoute,
} as any)
const VpseaAnnouncementsRoute = VpseaAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => VpseaRoute,
} as any)
const VpseaAnalyticsRoute = VpseaAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => VpseaRoute,
} as any)
const UnifastTesRoute = UnifastTesRouteImport.update({
  id: '/tes',
  path: '/tes',
  getParentRoute: () => UnifastRoute,
} as any)
const UnifastTdpRoute = UnifastTdpRouteImport.update({
  id: '/tdp',
  path: '/tdp',
  getParentRoute: () => UnifastRoute,
} as any)
const UnifastReportsRoute = UnifastReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => UnifastRoute,
} as any)
const UnifastLiquidationRoute = UnifastLiquidationRouteImport.update({
  id: '/liquidation',
  path: '/liquidation',
  getParentRoute: () => UnifastRoute,
} as any)
const UnifastFheRoute = UnifastFheRouteImport.update({
  id: '/fhe',
  path: '/fhe',
  getParentRoute: () => UnifastRoute,
} as any)
const UnifastDistributionRoute = UnifastDistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => UnifastRoute,
} as any)
const UnifastContinuingRoute = UnifastContinuingRouteImport.update({
  id: '/continuing',
  path: '/continuing',
  getParentRoute: () => UnifastRoute,
} as any)
const UnifastBillingRoute = UnifastBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => UnifastRoute,
} as any)
const UnifastAnalyticsRoute = UnifastAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => UnifastRoute,
} as any)
const SuperUsersRoute = SuperUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSettingsRoute = SuperSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperRoute,
} as any)
const SuperOfficesRoute = SuperOfficesRouteImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => SuperRoute,
} as any)
const SuperLogsRoute = SuperLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SuperRoute,
} as any)
const SuperCategoriesRoute = SuperCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SuperRoute,
} as any)
const SuperAnnouncementsRoute = SuperAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => SuperRoute,
} as any)
const StudentRecommendationsRoute = StudentRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentApplicationsRoute = StudentApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentApplyTdpRoute = StudentApplyTdpRouteImport.update({
  id: '/apply/tdp',
  path: '/apply/tdp',
  getParentRoute: () => StudentRoute,
} as any)
const StudentApplyAcademicRoute = StudentApplyAcademicRouteImport.update({
  id: '/apply/academic',
  path: '/apply/academic',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/super': typeof SuperRouteWithChildren
  '/unifast': typeof UnifastRouteWithChildren
  '/vpsea': typeof VpseaRouteWithChildren
  '/student/applications': typeof StudentApplicationsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/recommendations': typeof StudentRecommendationsRoute
  '/super/announcements': typeof SuperAnnouncementsRoute
  '/super/categories': typeof SuperCategoriesRoute
  '/super/logs': typeof SuperLogsRoute
  '/super/offices': typeof SuperOfficesRoute
  '/super/settings': typeof SuperSettingsRoute
  '/super/users': typeof SuperUsersRoute
  '/unifast/analytics': typeof UnifastAnalyticsRoute
  '/unifast/billing': typeof UnifastBillingRoute
  '/unifast/continuing': typeof UnifastContinuingRoute
  '/unifast/distribution': typeof UnifastDistributionRoute
  '/unifast/fhe': typeof UnifastFheRoute
  '/unifast/liquidation': typeof UnifastLiquidationRoute
  '/unifast/reports': typeof UnifastReportsRoute
  '/unifast/tdp': typeof UnifastTdpRoute
  '/unifast/tes': typeof UnifastTesRoute
  '/vpsea/analytics': typeof VpseaAnalyticsRoute
  '/vpsea/announcements': typeof VpseaAnnouncementsRoute
  '/vpsea/applications': typeof VpseaApplicationsRoute
  '/vpsea/archives': typeof VpseaArchivesRoute
  '/vpsea/renewals': typeof VpseaRenewalsRoute
  '/vpsea/reports': typeof VpseaReportsRoute
  '/vpsea/uploads': typeof VpseaUploadsRoute
  '/student/': typeof StudentIndexRoute
  '/super/': typeof SuperIndexRoute
  '/unifast/': typeof UnifastIndexRoute
  '/vpsea/': typeof VpseaIndexRoute
  '/student/apply/academic': typeof StudentApplyAcademicRoute
  '/student/apply/tdp': typeof StudentApplyTdpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/recommendations': typeof StudentRecommendationsRoute
  '/super/announcements': typeof SuperAnnouncementsRoute
  '/super/categories': typeof SuperCategoriesRoute
  '/super/logs': typeof SuperLogsRoute
  '/super/offices': typeof SuperOfficesRoute
  '/super/settings': typeof SuperSettingsRoute
  '/super/users': typeof SuperUsersRoute
  '/unifast/analytics': typeof UnifastAnalyticsRoute
  '/unifast/billing': typeof UnifastBillingRoute
  '/unifast/continuing': typeof UnifastContinuingRoute
  '/unifast/distribution': typeof UnifastDistributionRoute
  '/unifast/fhe': typeof UnifastFheRoute
  '/unifast/liquidation': typeof UnifastLiquidationRoute
  '/unifast/reports': typeof UnifastReportsRoute
  '/unifast/tdp': typeof UnifastTdpRoute
  '/unifast/tes': typeof UnifastTesRoute
  '/vpsea/analytics': typeof VpseaAnalyticsRoute
  '/vpsea/announcements': typeof VpseaAnnouncementsRoute
  '/vpsea/applications': typeof VpseaApplicationsRoute
  '/vpsea/archives': typeof VpseaArchivesRoute
  '/vpsea/renewals': typeof VpseaRenewalsRoute
  '/vpsea/reports': typeof VpseaReportsRoute
  '/vpsea/uploads': typeof VpseaUploadsRoute
  '/student': typeof StudentIndexRoute
  '/super': typeof SuperIndexRoute
  '/unifast': typeof UnifastIndexRoute
  '/vpsea': typeof VpseaIndexRoute
  '/student/apply/academic': typeof StudentApplyAcademicRoute
  '/student/apply/tdp': typeof StudentApplyTdpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/super': typeof SuperRouteWithChildren
  '/unifast': typeof UnifastRouteWithChildren
  '/vpsea': typeof VpseaRouteWithChildren
  '/student/applications': typeof StudentApplicationsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/recommendations': typeof StudentRecommendationsRoute
  '/super/announcements': typeof SuperAnnouncementsRoute
  '/super/categories': typeof SuperCategoriesRoute
  '/super/logs': typeof SuperLogsRoute
  '/super/offices': typeof SuperOfficesRoute
  '/super/settings': typeof SuperSettingsRoute
  '/super/users': typeof SuperUsersRoute
  '/unifast/analytics': typeof UnifastAnalyticsRoute
  '/unifast/billing': typeof UnifastBillingRoute
  '/unifast/continuing': typeof UnifastContinuingRoute
  '/unifast/distribution': typeof UnifastDistributionRoute
  '/unifast/fhe': typeof UnifastFheRoute
  '/unifast/liquidation': typeof UnifastLiquidationRoute
  '/unifast/reports': typeof UnifastReportsRoute
  '/unifast/tdp': typeof UnifastTdpRoute
  '/unifast/tes': typeof UnifastTesRoute
  '/vpsea/analytics': typeof VpseaAnalyticsRoute
  '/vpsea/announcements': typeof VpseaAnnouncementsRoute
  '/vpsea/applications': typeof VpseaApplicationsRoute
  '/vpsea/archives': typeof VpseaArchivesRoute
  '/vpsea/renewals': typeof VpseaRenewalsRoute
  '/vpsea/reports': typeof VpseaReportsRoute
  '/vpsea/uploads': typeof VpseaUploadsRoute
  '/student/': typeof StudentIndexRoute
  '/super/': typeof SuperIndexRoute
  '/unifast/': typeof UnifastIndexRoute
  '/vpsea/': typeof VpseaIndexRoute
  '/student/apply/academic': typeof StudentApplyAcademicRoute
  '/student/apply/tdp': typeof StudentApplyTdpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/student'
    | '/super'
    | '/unifast'
    | '/vpsea'
    | '/student/applications'
    | '/student/notifications'
    | '/student/recommendations'
    | '/super/announcements'
    | '/super/categories'
    | '/super/logs'
    | '/super/offices'
    | '/super/settings'
    | '/super/users'
    | '/unifast/analytics'
    | '/unifast/billing'
    | '/unifast/continuing'
    | '/unifast/distribution'
    | '/unifast/fhe'
    | '/unifast/liquidation'
    | '/unifast/reports'
    | '/unifast/tdp'
    | '/unifast/tes'
    | '/vpsea/analytics'
    | '/vpsea/announcements'
    | '/vpsea/applications'
    | '/vpsea/archives'
    | '/vpsea/renewals'
    | '/vpsea/reports'
    | '/vpsea/uploads'
    | '/student/'
    | '/super/'
    | '/unifast/'
    | '/vpsea/'
    | '/student/apply/academic'
    | '/student/apply/tdp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/student/applications'
    | '/student/notifications'
    | '/student/recommendations'
    | '/super/announcements'
    | '/super/categories'
    | '/super/logs'
    | '/super/offices'
    | '/super/settings'
    | '/super/users'
    | '/unifast/analytics'
    | '/unifast/billing'
    | '/unifast/continuing'
    | '/unifast/distribution'
    | '/unifast/fhe'
    | '/unifast/liquidation'
    | '/unifast/reports'
    | '/unifast/tdp'
    | '/unifast/tes'
    | '/vpsea/analytics'
    | '/vpsea/announcements'
    | '/vpsea/applications'
    | '/vpsea/archives'
    | '/vpsea/renewals'
    | '/vpsea/reports'
    | '/vpsea/uploads'
    | '/student'
    | '/super'
    | '/unifast'
    | '/vpsea'
    | '/student/apply/academic'
    | '/student/apply/tdp'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/student'
    | '/super'
    | '/unifast'
    | '/vpsea'
    | '/student/applications'
    | '/student/notifications'
    | '/student/recommendations'
    | '/super/announcements'
    | '/super/categories'
    | '/super/logs'
    | '/super/offices'
    | '/super/settings'
    | '/super/users'
    | '/unifast/analytics'
    | '/unifast/billing'
    | '/unifast/continuing'
    | '/unifast/distribution'
    | '/unifast/fhe'
    | '/unifast/liquidation'
    | '/unifast/reports'
    | '/unifast/tdp'
    | '/unifast/tes'
    | '/vpsea/analytics'
    | '/vpsea/announcements'
    | '/vpsea/applications'
    | '/vpsea/archives'
    | '/vpsea/renewals'
    | '/vpsea/reports'
    | '/vpsea/uploads'
    | '/student/'
    | '/super/'
    | '/unifast/'
    | '/vpsea/'
    | '/student/apply/academic'
    | '/student/apply/tdp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRouteWithChildren
  SuperRoute: typeof SuperRouteWithChildren
  UnifastRoute: typeof UnifastRouteWithChildren
  VpseaRoute: typeof VpseaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vpsea': {
      id: '/vpsea'
      path: '/vpsea'
      fullPath: '/vpsea'
      preLoaderRoute: typeof VpseaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unifast': {
      id: '/unifast'
      path: '/unifast'
      fullPath: '/unifast'
      preLoaderRoute: typeof UnifastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vpsea/': {
      id: '/vpsea/'
      path: '/'
      fullPath: '/vpsea/'
      preLoaderRoute: typeof VpseaIndexRouteImport
      parentRoute: typeof VpseaRoute
    }
    '/unifast/': {
      id: '/unifast/'
      path: '/'
      fullPath: '/unifast/'
      preLoaderRoute: typeof UnifastIndexRouteImport
      parentRoute: typeof UnifastRoute
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/vpsea/uploads': {
      id: '/vpsea/uploads'
      path: '/uploads'
      fullPath: '/vpsea/uploads'
      preLoaderRoute: typeof VpseaUploadsRouteImport
      parentRoute: typeof VpseaRoute
    }
    '/vpsea/reports': {
      id: '/vpsea/reports'
      path: '/reports'
      fullPath: '/vpsea/reports'
      preLoaderRoute: typeof VpseaReportsRouteImport
      parentRoute: typeof VpseaRoute
    }
    '/vpsea/renewals': {
      id: '/vpsea/renewals'
      path: '/renewals'
      fullPath: '/vpsea/renewals'
      preLoaderRoute: typeof VpseaRenewalsRouteImport
      parentRoute: typeof VpseaRoute
    }
    '/vpsea/archives': {
      id: '/vpsea/archives'
      path: '/archives'
      fullPath: '/vpsea/archives'
      preLoaderRoute: typeof VpseaArchivesRouteImport
      parentRoute: typeof VpseaRoute
    }
    '/vpsea/applications': {
      id: '/vpsea/applications'
      path: '/applications'
      fullPath: '/vpsea/applications'
      preLoaderRoute: typeof VpseaApplicationsRouteImport
      parentRoute: typeof VpseaRoute
    }
    '/vpsea/announcements': {
      id: '/vpsea/announcements'
      path: '/announcements'
      fullPath: '/vpsea/announcements'
      preLoaderRoute: typeof VpseaAnnouncementsRouteImport
      parentRoute: typeof VpseaRoute
    }
    '/vpsea/analytics': {
      id: '/vpsea/analytics'
      path: '/analytics'
      fullPath: '/vpsea/analytics'
      preLoaderRoute: typeof VpseaAnalyticsRouteImport
      parentRoute: typeof VpseaRoute
    }
    '/unifast/tes': {
      id: '/unifast/tes'
      path: '/tes'
      fullPath: '/unifast/tes'
      preLoaderRoute: typeof UnifastTesRouteImport
      parentRoute: typeof UnifastRoute
    }
    '/unifast/tdp': {
      id: '/unifast/tdp'
      path: '/tdp'
      fullPath: '/unifast/tdp'
      preLoaderRoute: typeof UnifastTdpRouteImport
      parentRoute: typeof UnifastRoute
    }
    '/unifast/reports': {
      id: '/unifast/reports'
      path: '/reports'
      fullPath: '/unifast/reports'
      preLoaderRoute: typeof UnifastReportsRouteImport
      parentRoute: typeof UnifastRoute
    }
    '/unifast/liquidation': {
      id: '/unifast/liquidation'
      path: '/liquidation'
      fullPath: '/unifast/liquidation'
      preLoaderRoute: typeof UnifastLiquidationRouteImport
      parentRoute: typeof UnifastRoute
    }
    '/unifast/fhe': {
      id: '/unifast/fhe'
      path: '/fhe'
      fullPath: '/unifast/fhe'
      preLoaderRoute: typeof UnifastFheRouteImport
      parentRoute: typeof UnifastRoute
    }
    '/unifast/distribution': {
      id: '/unifast/distribution'
      path: '/distribution'
      fullPath: '/unifast/distribution'
      preLoaderRoute: typeof UnifastDistributionRouteImport
      parentRoute: typeof UnifastRoute
    }
    '/unifast/continuing': {
      id: '/unifast/continuing'
      path: '/continuing'
      fullPath: '/unifast/continuing'
      preLoaderRoute: typeof UnifastContinuingRouteImport
      parentRoute: typeof UnifastRoute
    }
    '/unifast/billing': {
      id: '/unifast/billing'
      path: '/billing'
      fullPath: '/unifast/billing'
      preLoaderRoute: typeof UnifastBillingRouteImport
      parentRoute: typeof UnifastRoute
    }
    '/unifast/analytics': {
      id: '/unifast/analytics'
      path: '/analytics'
      fullPath: '/unifast/analytics'
      preLoaderRoute: typeof UnifastAnalyticsRouteImport
      parentRoute: typeof UnifastRoute
    }
    '/super/users': {
      id: '/super/users'
      path: '/users'
      fullPath: '/super/users'
      preLoaderRoute: typeof SuperUsersRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/settings': {
      id: '/super/settings'
      path: '/settings'
      fullPath: '/super/settings'
      preLoaderRoute: typeof SuperSettingsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/offices': {
      id: '/super/offices'
      path: '/offices'
      fullPath: '/super/offices'
      preLoaderRoute: typeof SuperOfficesRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/logs': {
      id: '/super/logs'
      path: '/logs'
      fullPath: '/super/logs'
      preLoaderRoute: typeof SuperLogsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/categories': {
      id: '/super/categories'
      path: '/categories'
      fullPath: '/super/categories'
      preLoaderRoute: typeof SuperCategoriesRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/announcements': {
      id: '/super/announcements'
      path: '/announcements'
      fullPath: '/super/announcements'
      preLoaderRoute: typeof SuperAnnouncementsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/student/recommendations': {
      id: '/student/recommendations'
      path: '/recommendations'
      fullPath: '/student/recommendations'
      preLoaderRoute: typeof StudentRecommendationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/applications': {
      id: '/student/applications'
      path: '/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof StudentApplicationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/apply/tdp': {
      id: '/student/apply/tdp'
      path: '/apply/tdp'
      fullPath: '/student/apply/tdp'
      preLoaderRoute: typeof StudentApplyTdpRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/apply/academic': {
      id: '/student/apply/academic'
      path: '/apply/academic'
      fullPath: '/student/apply/academic'
      preLoaderRoute: typeof StudentApplyAcademicRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface StudentRouteChildren {
  StudentApplicationsRoute: typeof StudentApplicationsRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentRecommendationsRoute: typeof StudentRecommendationsRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentApplyAcademicRoute: typeof StudentApplyAcademicRoute
  StudentApplyTdpRoute: typeof StudentApplyTdpRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentApplicationsRoute: StudentApplicationsRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentRecommendationsRoute: StudentRecommendationsRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentApplyAcademicRoute: StudentApplyAcademicRoute,
  StudentApplyTdpRoute: StudentApplyTdpRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface SuperRouteChildren {
  SuperAnnouncementsRoute: typeof SuperAnnouncementsRoute
  SuperCategoriesRoute: typeof SuperCategoriesRoute
  SuperLogsRoute: typeof SuperLogsRoute
  SuperOfficesRoute: typeof SuperOfficesRoute
  SuperSettingsRoute: typeof SuperSettingsRoute
  SuperUsersRoute: typeof SuperUsersRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperAnnouncementsRoute: SuperAnnouncementsRoute,
  SuperCategoriesRoute: SuperCategoriesRoute,
  SuperLogsRoute: SuperLogsRoute,
  SuperOfficesRoute: SuperOfficesRoute,
  SuperSettingsRoute: SuperSettingsRoute,
  SuperUsersRoute: SuperUsersRoute,
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

interface UnifastRouteChildren {
  UnifastAnalyticsRoute: typeof UnifastAnalyticsRoute
  UnifastBillingRoute: typeof UnifastBillingRoute
  UnifastContinuingRoute: typeof UnifastContinuingRoute
  UnifastDistributionRoute: typeof UnifastDistributionRoute
  UnifastFheRoute: typeof UnifastFheRoute
  UnifastLiquidationRoute: typeof UnifastLiquidationRoute
  UnifastReportsRoute: typeof UnifastReportsRoute
  UnifastTdpRoute: typeof UnifastTdpRoute
  UnifastTesRoute: typeof UnifastTesRoute
  UnifastIndexRoute: typeof UnifastIndexRoute
}

const UnifastRouteChildren: UnifastRouteChildren = {
  UnifastAnalyticsRoute: UnifastAnalyticsRoute,
  UnifastBillingRoute: UnifastBillingRoute,
  UnifastContinuingRoute: UnifastContinuingRoute,
  UnifastDistributionRoute: UnifastDistributionRoute,
  UnifastFheRoute: UnifastFheRoute,
  UnifastLiquidationRoute: UnifastLiquidationRoute,
  UnifastReportsRoute: UnifastReportsRoute,
  UnifastTdpRoute: UnifastTdpRoute,
  UnifastTesRoute: UnifastTesRoute,
  UnifastIndexRoute: UnifastIndexRoute,
}

const UnifastRouteWithChildren =
  UnifastRoute._addFileChildren(UnifastRouteChildren)

interface VpseaRouteChildren {
  VpseaAnalyticsRoute: typeof VpseaAnalyticsRoute
  VpseaAnnouncementsRoute: typeof VpseaAnnouncementsRoute
  VpseaApplicationsRoute: typeof VpseaApplicationsRoute
  VpseaArchivesRoute: typeof VpseaArchivesRoute
  VpseaRenewalsRoute: typeof VpseaRenewalsRoute
  VpseaReportsRoute: typeof VpseaReportsRoute
  VpseaUploadsRoute: typeof VpseaUploadsRoute
  VpseaIndexRoute: typeof VpseaIndexRoute
}

const VpseaRouteChildren: VpseaRouteChildren = {
  VpseaAnalyticsRoute: VpseaAnalyticsRoute,
  VpseaAnnouncementsRoute: VpseaAnnouncementsRoute,
  VpseaApplicationsRoute: VpseaApplicationsRoute,
  VpseaArchivesRoute: VpseaArchivesRoute,
  VpseaRenewalsRoute: VpseaRenewalsRoute,
  VpseaReportsRoute: VpseaReportsRoute,
  VpseaUploadsRoute: VpseaUploadsRoute,
  VpseaIndexRoute: VpseaIndexRoute,
}

const VpseaRouteWithChildren = VpseaRoute._addFileChildren(VpseaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRouteWithChildren,
  SuperRoute: SuperRouteWithChildren,
  UnifastRoute: UnifastRouteWithChildren,
  VpseaRoute: VpseaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
